#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

function parseArgs(argv) {
  return new Set(argv.slice(2));
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function readUtf8(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function writeUtf8(filePath, content) {
  fs.writeFileSync(filePath, content, "utf8");
}

function main() {
  const args = parseArgs(process.argv);
  const repoRoot = path.resolve(__dirname, "..");
  const distDir = path.join(repoRoot, "dist");
  const outFile = path.join(distDir, "printform.js");

  if (args.has("--clean")) {
    if (fs.existsSync(outFile)) {
      fs.unlinkSync(outFile);
    }
    return;
  }

  const sources = [
    "js/printform/helpers.js",
    "js/printform/config.js",
    "js/printform/dom.js",
    "js/printform/text.js",
    "js/printform/formatter.js",
    "js/printform.js"
  ].map((relativePath) => path.join(repoRoot, relativePath));

  const missing = sources.filter((filePath) => !fs.existsSync(filePath));
  if (missing.length) {
    throw new Error(`Missing source files:\\n${missing.join("\\n")}`);
  }

  const header = [
    "/*",
    " * PrintForm.js (bundle)",
    " * Generated by scripts/build.js",
    " * Source order:",
    sources.map((filePath) => ` * - ${path.relative(repoRoot, filePath).replace(/\\\\/g, "/")}`).join("\n"),
    " */",
    ""
  ].join("\n");

  const body = sources.map((filePath) => readUtf8(filePath).replace(/\r\n/g, "\n")).join("\n\n");
  const bundled = `${header}${body}\n`;

  ensureDir(distDir);
  writeUtf8(outFile, bundled);
}

try {
  main();
} catch (error) {
  console.error(error && error.stack ? error.stack : String(error));
  process.exitCode = 1;
}

